# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
env:
    NODE_VERSION: "14.x"

on: [push]

jobs:    
    publish-dev:
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{env.NODE_VERSION}}
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm run build
            - name: Force push branch
              uses: dfm/force-push-branch-action@v1
              with:
                target-branch: "build"
                commit-message: "Committing automatically from GitHub Actions"
                path: /
